/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  serial,
  varchar,
  timestamp,
  numeric,
  jsonb,
  boolean,
  text,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_roles = pgEnum('enum_users_roles', ['super-admin', 'admin', 'customer'])
export const enum_orders_timeline_type = pgEnum('enum_orders_timeline_type', [
  'note',
  'order_created',
  'order_paid',
  'order_cancelled',
  'refund_issued',
  'fulfillment_started',
  'shipped',
  'delivered',
  'return_requested',
  'return_completed',
  'other',
])
export const enum_orders_source = pgEnum('enum_orders_source', ['manual', 'api'])
export const enum_orders_payment_status = pgEnum('enum_orders_payment_status', [
  'pending',
  'paid',
  'failed',
  'refunded',
])
export const enum_orders_order_status = pgEnum('enum_orders_order_status', [
  'pending',
  'processing',
  'shipped',
  'delivered',
  'canceled',
])
export const enum_attributes_swatch_type = pgEnum('enum_attributes_swatch_type', [
  'label',
  'color',
  'image',
])
export const enum_products_sales_channels = pgEnum('enum_products_sales_channels', [
  'all',
  'onlineStore',
  'pos',
  'mobileApp',
])
export const enum_products_source = pgEnum('enum_products_source', ['manual'])
export const enum_products_type = pgEnum('enum_products_type', ['simple', 'variable'])
export const enum_gift_cards_type = pgEnum('enum_gift_cards_type', ['percent', 'amount'])
export const enum_payments_blocks_manual_method_type = pgEnum(
  'enum_payments_blocks_manual_method_type',
  ['cod', 'bankTransfer', 'inStore', 'other'],
)
export const enum_exports_format = pgEnum('enum_exports_format', ['csv', 'json'])
export const enum_exports_drafts = pgEnum('enum_exports_drafts', ['yes', 'no'])
export const enum_payload_jobs_log_task_slug = pgEnum('enum_payload_jobs_log_task_slug', [
  'inline',
  'createCollectionExport',
])
export const enum_payload_jobs_log_state = pgEnum('enum_payload_jobs_log_state', [
  'failed',
  'succeeded',
])
export const enum_payload_jobs_task_slug = pgEnum('enum_payload_jobs_task_slug', [
  'inline',
  'createCollectionExport',
])

export const users_roles = pgTable(
  'users_roles',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_users_roles('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('users_roles_order_idx').on(columns.order),
    index('users_roles_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [users.id],
      name: 'users_roles_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    firstName: varchar('first_name'),
    lastName: varchar('last_name'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const orders_timeline = pgTable(
  'orders_timeline',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    type: enum_orders_timeline_type('type').notNull(),
    createdBy: integer('created_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    details: varchar('details'),
  },
  (columns) => [
    index('orders_timeline_order_idx').on(columns._order),
    index('orders_timeline_parent_id_idx').on(columns._parentID),
    index('orders_timeline_created_by_idx').on(columns.createdBy),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [orders.id],
      name: 'orders_timeline_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const orders = pgTable(
  'orders',
  {
    id: serial('id').primaryKey(),
    orderId: varchar('order_id').notNull(),
    totalAmount: numeric('total_amount', { mode: 'number' }).notNull(),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    cart: integer('cart_id').references(() => carts.id, {
      onDelete: 'set null',
    }),
    source: enum_orders_source('source').default('manual'),
    currency: varchar('currency').notNull(),
    paymentStatus: enum_orders_payment_status('payment_status').notNull().default('pending'),
    orderStatus: enum_orders_order_status('order_status').notNull().default('pending'),
    payment: integer('payment_id').references(() => payments.id, {
      onDelete: 'set null',
    }),
    shipping: integer('shipping_id').references(() => shipping.id, {
      onDelete: 'set null',
    }),
    paymentIntentId: varchar('payment_intent_id'),
    sessionId: varchar('session_id'),
    sessionUrl: varchar('session_url'),
    paymentMethod: varchar('payment_method'),
    receiptUrl: varchar('receipt_url'),
    metadata: jsonb('metadata'),
    shippingAddress: jsonb('shipping_address'),
    billingAddress: jsonb('billing_address'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('orders_order_id_idx').on(columns.orderId),
    index('orders_user_idx').on(columns.user),
    index('orders_cart_idx').on(columns.cart),
    index('orders_payment_idx').on(columns.payment),
    index('orders_shipping_idx').on(columns.shipping),
    index('orders_updated_at_idx').on(columns.updatedAt),
    index('orders_created_at_idx').on(columns.createdAt),
  ],
)

export const carts_cart_items = pgTable(
  'carts_cart_items',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    variantId: varchar('variant_id').notNull(),
    product: integer('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    quantity: numeric('quantity', { mode: 'number' }).notNull(),
  },
  (columns) => [
    index('carts_cart_items_order_idx').on(columns._order),
    index('carts_cart_items_parent_id_idx').on(columns._parentID),
    index('carts_cart_items_product_idx').on(columns.product),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [carts.id],
      name: 'carts_cart_items_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const carts = pgTable(
  'carts',
  {
    id: serial('id').primaryKey(),
    sessionId: varchar('session_id').notNull(),
    customer: integer('customer_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    completed: boolean('completed').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('carts_customer_idx').on(columns.customer),
    index('carts_updated_at_idx').on(columns.updatedAt),
    index('carts_created_at_idx').on(columns.createdAt),
  ],
)

export const collections = pgTable(
  'collections',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    featured: boolean('featured').default(false),
    visible: boolean('visible').default(true),
    handle: varchar('handle'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('collections_image_idx').on(columns.image),
    index('collections_handle_idx').on(columns.handle),
    index('collections_updated_at_idx').on(columns.updatedAt),
    index('collections_created_at_idx').on(columns.createdAt),
  ],
)

export const attributes = pgTable(
  'attributes',
  {
    id: serial('id').primaryKey(),
    handle: varchar('handle'),
    name: varchar('name').notNull(),
    swatchType: enum_attributes_swatch_type('swatch_type').notNull().default('label'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('attributes_handle_idx').on(columns.handle),
    index('attributes_updated_at_idx').on(columns.updatedAt),
    index('attributes_created_at_idx').on(columns.createdAt),
  ],
)

export const attribute_values = pgTable(
  'attribute_values',
  {
    id: serial('id').primaryKey(),
    attribute: integer('attribute_id')
      .notNull()
      .references(() => attributes.id, {
        onDelete: 'set null',
      }),
    label: varchar('label').notNull(),
    handle: varchar('handle'),
    colorHex: varchar('color_hex'),
    swatchImage: integer('swatch_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('attribute_values_attribute_idx').on(columns.attribute),
    index('attribute_values_handle_idx').on(columns.handle),
    index('attribute_values_swatch_image_idx').on(columns.swatchImage),
    index('attribute_values_updated_at_idx').on(columns.updatedAt),
    index('attribute_values_created_at_idx').on(columns.createdAt),
  ],
)

export const products_sales_channels = pgTable(
  'products_sales_channels',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_products_sales_channels('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('products_sales_channels_order_idx').on(columns.order),
    index('products_sales_channels_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_sales_channels_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const products_attributes = pgTable(
  'products_attributes',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    attribute: integer('attribute_id')
      .notNull()
      .references(() => attributes.id, {
        onDelete: 'set null',
      }),
    variation: boolean('variation'),
    visible: boolean('visible'),
  },
  (columns) => [
    index('products_attributes_order_idx').on(columns._order),
    index('products_attributes_parent_id_idx').on(columns._parentID),
    index('products_attributes_attribute_idx').on(columns.attribute),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_attributes_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_variant_options = pgTable(
  'products_variant_options',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    option: varchar('option').notNull(),
  },
  (columns) => [
    index('products_variant_options_order_idx').on(columns._order),
    index('products_variant_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_variant_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_variants_options = pgTable(
  'products_variants_options',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    option: varchar('option').notNull(),
    value: varchar('value').notNull(),
  },
  (columns) => [
    index('products_variants_options_order_idx').on(columns._order),
    index('products_variants_options_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products_variants.id],
      name: 'products_variants_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_variants = pgTable(
  'products_variants',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    vid: varchar('vid'),
    sku: varchar('sku'),
    price: numeric('price', { mode: 'number' }).notNull(),
    originalPrice: numeric('original_price', { mode: 'number' }),
    stockCount: numeric('stock_count', { mode: 'number' }).default(0),
  },
  (columns) => [
    index('products_variants_order_idx').on(columns._order),
    index('products_variants_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_variants_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products_custom_fields = pgTable(
  'products_custom_fields',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').notNull(),
    value: varchar('value'),
  },
  (columns) => [
    index('products_custom_fields_order_idx').on(columns._order),
    index('products_custom_fields_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [products.id],
      name: 'products_custom_fields_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const products = pgTable(
  'products',
  {
    id: serial('id').primaryKey(),
    pid: varchar('pid'),
    title: varchar('title').notNull(),
    currency: varchar('currency'),
    visible: boolean('visible').default(true),
    featured: boolean('featured').default(false),
    inStock: boolean('in_stock').default(true),
    source: enum_products_source('source').default('manual'),
    handle: varchar('handle'),
    description: varchar('description'),
    meta_title: varchar('meta_title'),
    meta_description: varchar('meta_description'),
    type: enum_products_type('type').notNull().default('simple'),
    price: numeric('price', { mode: 'number' }).default(0),
    originalPrice: numeric('original_price', { mode: 'number' }),
    stockManage: boolean('stock_manage'),
    backOrders: boolean('back_orders'),
    stockCount: numeric('stock_count', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('products_handle_idx').on(columns.handle),
    index('products_updated_at_idx').on(columns.updatedAt),
    index('products_created_at_idx').on(columns.createdAt),
  ],
)

export const products_texts = pgTable(
  'products_texts',
  {
    id: serial('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    text: varchar('text'),
  },
  (columns) => [
    index('products_texts_order_parent').on(columns.order, columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_texts_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const products_rels = pgTable(
  'products_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    collectionsID: integer('collections_id'),
    'attribute-valuesID': integer('attribute_values_id'),
    variantsID: integer('variants_id'),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('products_rels_order_idx').on(columns.order),
    index('products_rels_parent_idx').on(columns.parent),
    index('products_rels_path_idx').on(columns.path),
    index('products_rels_collections_id_idx').on(columns.collectionsID),
    index('products_rels_attribute_values_id_idx').on(columns['attribute-valuesID']),
    index('products_rels_variants_id_idx').on(columns.variantsID),
    index('products_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [products.id],
      name: 'products_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['collectionsID']],
      foreignColumns: [collections.id],
      name: 'products_rels_collections_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['attribute-valuesID']],
      foreignColumns: [attribute_values.id],
      name: 'products_rels_attribute_values_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['variantsID']],
      foreignColumns: [variants.id],
      name: 'products_rels_variants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'products_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const variants_attribute_options = pgTable(
  'variants_attribute_options',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    attribute: integer('attribute_id')
      .notNull()
      .references(() => attributes.id, {
        onDelete: 'set null',
      }),
    value: integer('value_id')
      .notNull()
      .references(() => attribute_values.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('variants_attribute_options_order_idx').on(columns._order),
    index('variants_attribute_options_parent_id_idx').on(columns._parentID),
    index('variants_attribute_options_attribute_idx').on(columns.attribute),
    index('variants_attribute_options_value_idx').on(columns.value),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [variants.id],
      name: 'variants_attribute_options_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const variants = pgTable(
  'variants',
  {
    id: serial('id').primaryKey(),
    price: numeric('price', { mode: 'number' }).notNull(),
    originalPrice: numeric('original_price', { mode: 'number' }),
    stockManage: boolean('stock_manage'),
    stockCount: numeric('stock_count', { mode: 'number' }).notNull().default(0),
    product: integer('product_id')
      .notNull()
      .references(() => products.id, {
        onDelete: 'set null',
      }),
    sku: varchar('sku').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('variants_product_idx').on(columns.product),
    uniqueIndex('variants_sku_idx').on(columns.sku),
    index('variants_updated_at_idx').on(columns.updatedAt),
    index('variants_created_at_idx').on(columns.createdAt),
  ],
)

export const variants_rels = pgTable(
  'variants_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    mediaID: integer('media_id'),
  },
  (columns) => [
    index('variants_rels_order_idx').on(columns.order),
    index('variants_rels_parent_idx').on(columns.parent),
    index('variants_rels_path_idx').on(columns.path),
    index('variants_rels_media_id_idx').on(columns.mediaID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [variants.id],
      name: 'variants_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'variants_rels_media_fk',
    }).onDelete('cascade'),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const policies = pgTable(
  'policies',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    description: varchar('description'),
    handle: varchar('handle'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('policies_handle_idx').on(columns.handle),
    index('policies_updated_at_idx').on(columns.updatedAt),
    index('policies_created_at_idx').on(columns.createdAt),
  ],
)

export const gift_cards = pgTable(
  'gift_cards',
  {
    id: serial('id').primaryKey(),
    code: varchar('code').notNull(),
    type: enum_gift_cards_type('type').notNull().default('amount'),
    value: numeric('value', { mode: 'number' }).notNull(),
    expiryDate: timestamp('expiry_date', { mode: 'string', withTimezone: true, precision: 3 }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('gift_cards_updated_at_idx').on(columns.updatedAt),
    index('gift_cards_created_at_idx').on(columns.createdAt),
  ],
)

export const gift_cards_rels = pgTable(
  'gift_cards_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('gift_cards_rels_order_idx').on(columns.order),
    index('gift_cards_rels_parent_idx').on(columns.parent),
    index('gift_cards_rels_path_idx').on(columns.path),
    index('gift_cards_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [gift_cards.id],
      name: 'gift_cards_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'gift_cards_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull().default('New Page'),
    description: varchar('description'),
    handle: varchar('handle').notNull().default('new-page'),
    page: jsonb('page').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const payments_blocks_manual_details = pgTable(
  'payments_blocks_manual_details',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label'),
    value: varchar('value'),
  },
  (columns) => [
    index('payments_blocks_manual_details_order_idx').on(columns._order),
    index('payments_blocks_manual_details_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payments_blocks_manual.id],
      name: 'payments_blocks_manual_details_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payments_blocks_manual = pgTable(
  'payments_blocks_manual',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    methodType: enum_payments_blocks_manual_method_type('method_type').notNull(),
    instructions: varchar('instructions').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('payments_blocks_manual_order_idx').on(columns._order),
    index('payments_blocks_manual_parent_id_idx').on(columns._parentID),
    index('payments_blocks_manual_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payments.id],
      name: 'payments_blocks_manual_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payments = pgTable(
  'payments',
  {
    id: serial('id').primaryKey(),
    _order: varchar('_order'),
    name: varchar('name').notNull(),
    enabled: boolean('enabled').default(true),
    fee: numeric('fee', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payments__order_idx').on(columns._order),
    index('payments_updated_at_idx').on(columns.updatedAt),
    index('payments_created_at_idx').on(columns.createdAt),
  ],
)

export const locations = pgTable(
  'locations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    address: varchar('address').notNull(),
    latitude: numeric('latitude', { mode: 'number' }),
    longitude: numeric('longitude', { mode: 'number' }),
    contactPhone: varchar('contact_phone'),
    hours: varchar('hours'),
    enabled: boolean('enabled').default(true),
    isPickupLocation: boolean('is_pickup_location').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('locations_updated_at_idx').on(columns.updatedAt),
    index('locations_created_at_idx').on(columns.createdAt),
  ],
)

export const shipping_blocks_custom_shipping = pgTable(
  'shipping_blocks_custom_shipping',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    baseRate: numeric('base_rate', { mode: 'number' }).notNull(),
    freeShippingMinOrder: numeric('free_shipping_min_order', { mode: 'number' }),
    estimatedDeliveryDays: varchar('estimated_delivery_days'),
    notes: varchar('notes'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('shipping_blocks_custom_shipping_order_idx').on(columns._order),
    index('shipping_blocks_custom_shipping_parent_id_idx').on(columns._parentID),
    index('shipping_blocks_custom_shipping_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [shipping.id],
      name: 'shipping_blocks_custom_shipping_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const shipping = pgTable(
  'shipping',
  {
    id: serial('id').primaryKey(),
    _order: varchar('_order'),
    name: varchar('name').notNull(),
    enabled: boolean('enabled').default(true),
    location: integer('location_id').references(() => locations.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('shipping__order_idx').on(columns._order),
    index('shipping_location_idx').on(columns.location),
    index('shipping_updated_at_idx').on(columns.updatedAt),
    index('shipping_created_at_idx').on(columns.createdAt),
  ],
)

export const exports = pgTable(
  'exports',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    format: enum_exports_format('format').notNull().default('csv'),
    limit: numeric('limit', { mode: 'number' }),
    sort: varchar('sort'),
    drafts: enum_exports_drafts('drafts').default('yes'),
    collectionSlug: varchar('collection_slug').notNull(),
    where: jsonb('where').default(sql`'{}'::jsonb`),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('exports_updated_at_idx').on(columns.updatedAt),
    index('exports_created_at_idx').on(columns.createdAt),
    uniqueIndex('exports_filename_idx').on(columns.filename),
  ],
)

export const exports_texts = pgTable(
  'exports_texts',
  {
    id: serial('id').primaryKey(),
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    text: varchar('text'),
  },
  (columns) => [
    index('exports_texts_order_parent').on(columns.order, columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [exports.id],
      name: 'exports_texts_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_jobs_log = pgTable(
  'payload_jobs_log',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    executedAt: timestamp('executed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp('completed_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug('task_slug').notNull(),
    taskID: varchar('task_i_d').notNull(),
    input: jsonb('input'),
    output: jsonb('output'),
    state: enum_payload_jobs_log_state('state').notNull(),
    error: jsonb('error'),
  },
  (columns) => [
    index('payload_jobs_log_order_idx').on(columns._order),
    index('payload_jobs_log_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [payload_jobs.id],
      name: 'payload_jobs_log_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_jobs = pgTable(
  'payload_jobs',
  {
    id: serial('id').primaryKey(),
    input: jsonb('input'),
    completedAt: timestamp('completed_at', { mode: 'string', withTimezone: true, precision: 3 }),
    totalTried: numeric('total_tried', { mode: 'number' }).default(0),
    hasError: boolean('has_error').default(false),
    error: jsonb('error'),
    taskSlug: enum_payload_jobs_task_slug('task_slug'),
    queue: varchar('queue').default('default'),
    waitUntil: timestamp('wait_until', { mode: 'string', withTimezone: true, precision: 3 }),
    processing: boolean('processing').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_jobs_completed_at_idx').on(columns.completedAt),
    index('payload_jobs_total_tried_idx').on(columns.totalTried),
    index('payload_jobs_has_error_idx').on(columns.hasError),
    index('payload_jobs_task_slug_idx').on(columns.taskSlug),
    index('payload_jobs_queue_idx').on(columns.queue),
    index('payload_jobs_wait_until_idx').on(columns.waitUntil),
    index('payload_jobs_processing_idx').on(columns.processing),
    index('payload_jobs_updated_at_idx').on(columns.updatedAt),
    index('payload_jobs_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    ordersID: integer('orders_id'),
    cartsID: integer('carts_id'),
    collectionsID: integer('collections_id'),
    attributesID: integer('attributes_id'),
    'attribute-valuesID': integer('attribute_values_id'),
    productsID: integer('products_id'),
    variantsID: integer('variants_id'),
    mediaID: integer('media_id'),
    policiesID: integer('policies_id'),
    'gift-cardsID': integer('gift_cards_id'),
    pagesID: integer('pages_id'),
    paymentsID: integer('payments_id'),
    locationsID: integer('locations_id'),
    shippingID: integer('shipping_id'),
    exportsID: integer('exports_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_orders_id_idx').on(columns.ordersID),
    index('payload_locked_documents_rels_carts_id_idx').on(columns.cartsID),
    index('payload_locked_documents_rels_collections_id_idx').on(columns.collectionsID),
    index('payload_locked_documents_rels_attributes_id_idx').on(columns.attributesID),
    index('payload_locked_documents_rels_attribute_values_id_idx').on(
      columns['attribute-valuesID'],
    ),
    index('payload_locked_documents_rels_products_id_idx').on(columns.productsID),
    index('payload_locked_documents_rels_variants_id_idx').on(columns.variantsID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_policies_id_idx').on(columns.policiesID),
    index('payload_locked_documents_rels_gift_cards_id_idx').on(columns['gift-cardsID']),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_payments_id_idx').on(columns.paymentsID),
    index('payload_locked_documents_rels_locations_id_idx').on(columns.locationsID),
    index('payload_locked_documents_rels_shipping_id_idx').on(columns.shippingID),
    index('payload_locked_documents_rels_exports_id_idx').on(columns.exportsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['ordersID']],
      foreignColumns: [orders.id],
      name: 'payload_locked_documents_rels_orders_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['cartsID']],
      foreignColumns: [carts.id],
      name: 'payload_locked_documents_rels_carts_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['collectionsID']],
      foreignColumns: [collections.id],
      name: 'payload_locked_documents_rels_collections_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['attributesID']],
      foreignColumns: [attributes.id],
      name: 'payload_locked_documents_rels_attributes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['attribute-valuesID']],
      foreignColumns: [attribute_values.id],
      name: 'payload_locked_documents_rels_attribute_values_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['productsID']],
      foreignColumns: [products.id],
      name: 'payload_locked_documents_rels_products_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['variantsID']],
      foreignColumns: [variants.id],
      name: 'payload_locked_documents_rels_variants_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['policiesID']],
      foreignColumns: [policies.id],
      name: 'payload_locked_documents_rels_policies_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['gift-cardsID']],
      foreignColumns: [gift_cards.id],
      name: 'payload_locked_documents_rels_gift_cards_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['paymentsID']],
      foreignColumns: [payments.id],
      name: 'payload_locked_documents_rels_payments_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['locationsID']],
      foreignColumns: [locations.id],
      name: 'payload_locked_documents_rels_locations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['shippingID']],
      foreignColumns: [shipping.id],
      name: 'payload_locked_documents_rels_shipping_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['exportsID']],
      foreignColumns: [exports.id],
      name: 'payload_locked_documents_rels_exports_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_roles = relations(users_roles, ({ one }) => ({
  parent: one(users, {
    fields: [users_roles.parent],
    references: [users.id],
    relationName: 'roles',
  }),
}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  roles: many(users_roles, {
    relationName: 'roles',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_orders_timeline = relations(orders_timeline, ({ one }) => ({
  _parentID: one(orders, {
    fields: [orders_timeline._parentID],
    references: [orders.id],
    relationName: 'timeline',
  }),
  createdBy: one(users, {
    fields: [orders_timeline.createdBy],
    references: [users.id],
    relationName: 'createdBy',
  }),
}))
export const relations_orders = relations(orders, ({ one, many }) => ({
  user: one(users, {
    fields: [orders.user],
    references: [users.id],
    relationName: 'user',
  }),
  cart: one(carts, {
    fields: [orders.cart],
    references: [carts.id],
    relationName: 'cart',
  }),
  payment: one(payments, {
    fields: [orders.payment],
    references: [payments.id],
    relationName: 'payment',
  }),
  shipping: one(shipping, {
    fields: [orders.shipping],
    references: [shipping.id],
    relationName: 'shipping',
  }),
  timeline: many(orders_timeline, {
    relationName: 'timeline',
  }),
}))
export const relations_carts_cart_items = relations(carts_cart_items, ({ one }) => ({
  _parentID: one(carts, {
    fields: [carts_cart_items._parentID],
    references: [carts.id],
    relationName: 'cartItems',
  }),
  product: one(products, {
    fields: [carts_cart_items.product],
    references: [products.id],
    relationName: 'product',
  }),
}))
export const relations_carts = relations(carts, ({ one, many }) => ({
  customer: one(users, {
    fields: [carts.customer],
    references: [users.id],
    relationName: 'customer',
  }),
  cartItems: many(carts_cart_items, {
    relationName: 'cartItems',
  }),
}))
export const relations_collections = relations(collections, ({ one }) => ({
  image: one(media, {
    fields: [collections.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_attributes = relations(attributes, () => ({}))
export const relations_attribute_values = relations(attribute_values, ({ one }) => ({
  attribute: one(attributes, {
    fields: [attribute_values.attribute],
    references: [attributes.id],
    relationName: 'attribute',
  }),
  swatchImage: one(media, {
    fields: [attribute_values.swatchImage],
    references: [media.id],
    relationName: 'swatchImage',
  }),
}))
export const relations_products_sales_channels = relations(products_sales_channels, ({ one }) => ({
  parent: one(products, {
    fields: [products_sales_channels.parent],
    references: [products.id],
    relationName: 'salesChannels',
  }),
}))
export const relations_products_attributes = relations(products_attributes, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_attributes._parentID],
    references: [products.id],
    relationName: 'attributes',
  }),
  attribute: one(attributes, {
    fields: [products_attributes.attribute],
    references: [attributes.id],
    relationName: 'attribute',
  }),
}))
export const relations_products_variant_options = relations(
  products_variant_options,
  ({ one }) => ({
    _parentID: one(products, {
      fields: [products_variant_options._parentID],
      references: [products.id],
      relationName: 'variantOptions',
    }),
  }),
)
export const relations_products_variants_options = relations(
  products_variants_options,
  ({ one }) => ({
    _parentID: one(products_variants, {
      fields: [products_variants_options._parentID],
      references: [products_variants.id],
      relationName: 'options',
    }),
  }),
)
export const relations_products_variants = relations(products_variants, ({ one, many }) => ({
  _parentID: one(products, {
    fields: [products_variants._parentID],
    references: [products.id],
    relationName: 'variants',
  }),
  options: many(products_variants_options, {
    relationName: 'options',
  }),
}))
export const relations_products_custom_fields = relations(products_custom_fields, ({ one }) => ({
  _parentID: one(products, {
    fields: [products_custom_fields._parentID],
    references: [products.id],
    relationName: 'customFields',
  }),
}))
export const relations_products_texts = relations(products_texts, ({ one }) => ({
  parent: one(products, {
    fields: [products_texts.parent],
    references: [products.id],
    relationName: '_texts',
  }),
}))
export const relations_products_rels = relations(products_rels, ({ one }) => ({
  parent: one(products, {
    fields: [products_rels.parent],
    references: [products.id],
    relationName: '_rels',
  }),
  collectionsID: one(collections, {
    fields: [products_rels.collectionsID],
    references: [collections.id],
    relationName: 'collections',
  }),
  'attribute-valuesID': one(attribute_values, {
    fields: [products_rels['attribute-valuesID']],
    references: [attribute_values.id],
    relationName: 'attribute-values',
  }),
  variantsID: one(variants, {
    fields: [products_rels.variantsID],
    references: [variants.id],
    relationName: 'variants',
  }),
  mediaID: one(media, {
    fields: [products_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_products = relations(products, ({ many }) => ({
  salesChannels: many(products_sales_channels, {
    relationName: 'salesChannels',
  }),
  attributes: many(products_attributes, {
    relationName: 'attributes',
  }),
  variantOptions: many(products_variant_options, {
    relationName: 'variantOptions',
  }),
  variants: many(products_variants, {
    relationName: 'variants',
  }),
  customFields: many(products_custom_fields, {
    relationName: 'customFields',
  }),
  _texts: many(products_texts, {
    relationName: '_texts',
  }),
  _rels: many(products_rels, {
    relationName: '_rels',
  }),
}))
export const relations_variants_attribute_options = relations(
  variants_attribute_options,
  ({ one }) => ({
    _parentID: one(variants, {
      fields: [variants_attribute_options._parentID],
      references: [variants.id],
      relationName: 'attributeOptions',
    }),
    attribute: one(attributes, {
      fields: [variants_attribute_options.attribute],
      references: [attributes.id],
      relationName: 'attribute',
    }),
    value: one(attribute_values, {
      fields: [variants_attribute_options.value],
      references: [attribute_values.id],
      relationName: 'value',
    }),
  }),
)
export const relations_variants_rels = relations(variants_rels, ({ one }) => ({
  parent: one(variants, {
    fields: [variants_rels.parent],
    references: [variants.id],
    relationName: '_rels',
  }),
  mediaID: one(media, {
    fields: [variants_rels.mediaID],
    references: [media.id],
    relationName: 'media',
  }),
}))
export const relations_variants = relations(variants, ({ one, many }) => ({
  product: one(products, {
    fields: [variants.product],
    references: [products.id],
    relationName: 'product',
  }),
  attributeOptions: many(variants_attribute_options, {
    relationName: 'attributeOptions',
  }),
  _rels: many(variants_rels, {
    relationName: '_rels',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_policies = relations(policies, () => ({}))
export const relations_gift_cards_rels = relations(gift_cards_rels, ({ one }) => ({
  parent: one(gift_cards, {
    fields: [gift_cards_rels.parent],
    references: [gift_cards.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [gift_cards_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_gift_cards = relations(gift_cards, ({ many }) => ({
  _rels: many(gift_cards_rels, {
    relationName: '_rels',
  }),
}))
export const relations_pages = relations(pages, () => ({}))
export const relations_payments_blocks_manual_details = relations(
  payments_blocks_manual_details,
  ({ one }) => ({
    _parentID: one(payments_blocks_manual, {
      fields: [payments_blocks_manual_details._parentID],
      references: [payments_blocks_manual.id],
      relationName: 'details',
    }),
  }),
)
export const relations_payments_blocks_manual = relations(
  payments_blocks_manual,
  ({ one, many }) => ({
    _parentID: one(payments, {
      fields: [payments_blocks_manual._parentID],
      references: [payments.id],
      relationName: '_blocks_manual',
    }),
    details: many(payments_blocks_manual_details, {
      relationName: 'details',
    }),
  }),
)
export const relations_payments = relations(payments, ({ many }) => ({
  _blocks_manual: many(payments_blocks_manual, {
    relationName: '_blocks_manual',
  }),
}))
export const relations_locations = relations(locations, () => ({}))
export const relations_shipping_blocks_custom_shipping = relations(
  shipping_blocks_custom_shipping,
  ({ one }) => ({
    _parentID: one(shipping, {
      fields: [shipping_blocks_custom_shipping._parentID],
      references: [shipping.id],
      relationName: '_blocks_custom-shipping',
    }),
  }),
)
export const relations_shipping = relations(shipping, ({ one, many }) => ({
  location: one(locations, {
    fields: [shipping.location],
    references: [locations.id],
    relationName: 'location',
  }),
  '_blocks_custom-shipping': many(shipping_blocks_custom_shipping, {
    relationName: '_blocks_custom-shipping',
  }),
}))
export const relations_exports_texts = relations(exports_texts, ({ one }) => ({
  parent: one(exports, {
    fields: [exports_texts.parent],
    references: [exports.id],
    relationName: '_texts',
  }),
}))
export const relations_exports = relations(exports, ({ many }) => ({
  _texts: many(exports_texts, {
    relationName: '_texts',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_jobs_log = relations(payload_jobs_log, ({ one }) => ({
  _parentID: one(payload_jobs, {
    fields: [payload_jobs_log._parentID],
    references: [payload_jobs.id],
    relationName: 'log',
  }),
}))
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: 'log',
  }),
}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    ordersID: one(orders, {
      fields: [payload_locked_documents_rels.ordersID],
      references: [orders.id],
      relationName: 'orders',
    }),
    cartsID: one(carts, {
      fields: [payload_locked_documents_rels.cartsID],
      references: [carts.id],
      relationName: 'carts',
    }),
    collectionsID: one(collections, {
      fields: [payload_locked_documents_rels.collectionsID],
      references: [collections.id],
      relationName: 'collections',
    }),
    attributesID: one(attributes, {
      fields: [payload_locked_documents_rels.attributesID],
      references: [attributes.id],
      relationName: 'attributes',
    }),
    'attribute-valuesID': one(attribute_values, {
      fields: [payload_locked_documents_rels['attribute-valuesID']],
      references: [attribute_values.id],
      relationName: 'attribute-values',
    }),
    productsID: one(products, {
      fields: [payload_locked_documents_rels.productsID],
      references: [products.id],
      relationName: 'products',
    }),
    variantsID: one(variants, {
      fields: [payload_locked_documents_rels.variantsID],
      references: [variants.id],
      relationName: 'variants',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    policiesID: one(policies, {
      fields: [payload_locked_documents_rels.policiesID],
      references: [policies.id],
      relationName: 'policies',
    }),
    'gift-cardsID': one(gift_cards, {
      fields: [payload_locked_documents_rels['gift-cardsID']],
      references: [gift_cards.id],
      relationName: 'gift-cards',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    paymentsID: one(payments, {
      fields: [payload_locked_documents_rels.paymentsID],
      references: [payments.id],
      relationName: 'payments',
    }),
    locationsID: one(locations, {
      fields: [payload_locked_documents_rels.locationsID],
      references: [locations.id],
      relationName: 'locations',
    }),
    shippingID: one(shipping, {
      fields: [payload_locked_documents_rels.shippingID],
      references: [shipping.id],
      relationName: 'shipping',
    }),
    exportsID: one(exports, {
      fields: [payload_locked_documents_rels.exportsID],
      references: [exports.id],
      relationName: 'exports',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_roles: typeof enum_users_roles
  enum_orders_timeline_type: typeof enum_orders_timeline_type
  enum_orders_source: typeof enum_orders_source
  enum_orders_payment_status: typeof enum_orders_payment_status
  enum_orders_order_status: typeof enum_orders_order_status
  enum_attributes_swatch_type: typeof enum_attributes_swatch_type
  enum_products_sales_channels: typeof enum_products_sales_channels
  enum_products_source: typeof enum_products_source
  enum_products_type: typeof enum_products_type
  enum_gift_cards_type: typeof enum_gift_cards_type
  enum_payments_blocks_manual_method_type: typeof enum_payments_blocks_manual_method_type
  enum_exports_format: typeof enum_exports_format
  enum_exports_drafts: typeof enum_exports_drafts
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug
  users_roles: typeof users_roles
  users_sessions: typeof users_sessions
  users: typeof users
  orders_timeline: typeof orders_timeline
  orders: typeof orders
  carts_cart_items: typeof carts_cart_items
  carts: typeof carts
  collections: typeof collections
  attributes: typeof attributes
  attribute_values: typeof attribute_values
  products_sales_channels: typeof products_sales_channels
  products_attributes: typeof products_attributes
  products_variant_options: typeof products_variant_options
  products_variants_options: typeof products_variants_options
  products_variants: typeof products_variants
  products_custom_fields: typeof products_custom_fields
  products: typeof products
  products_texts: typeof products_texts
  products_rels: typeof products_rels
  variants_attribute_options: typeof variants_attribute_options
  variants: typeof variants
  variants_rels: typeof variants_rels
  media: typeof media
  policies: typeof policies
  gift_cards: typeof gift_cards
  gift_cards_rels: typeof gift_cards_rels
  pages: typeof pages
  payments_blocks_manual_details: typeof payments_blocks_manual_details
  payments_blocks_manual: typeof payments_blocks_manual
  payments: typeof payments
  locations: typeof locations
  shipping_blocks_custom_shipping: typeof shipping_blocks_custom_shipping
  shipping: typeof shipping
  exports: typeof exports
  exports_texts: typeof exports_texts
  payload_kv: typeof payload_kv
  payload_jobs_log: typeof payload_jobs_log
  payload_jobs: typeof payload_jobs
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_roles: typeof relations_users_roles
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_orders_timeline: typeof relations_orders_timeline
  relations_orders: typeof relations_orders
  relations_carts_cart_items: typeof relations_carts_cart_items
  relations_carts: typeof relations_carts
  relations_collections: typeof relations_collections
  relations_attributes: typeof relations_attributes
  relations_attribute_values: typeof relations_attribute_values
  relations_products_sales_channels: typeof relations_products_sales_channels
  relations_products_attributes: typeof relations_products_attributes
  relations_products_variant_options: typeof relations_products_variant_options
  relations_products_variants_options: typeof relations_products_variants_options
  relations_products_variants: typeof relations_products_variants
  relations_products_custom_fields: typeof relations_products_custom_fields
  relations_products_texts: typeof relations_products_texts
  relations_products_rels: typeof relations_products_rels
  relations_products: typeof relations_products
  relations_variants_attribute_options: typeof relations_variants_attribute_options
  relations_variants_rels: typeof relations_variants_rels
  relations_variants: typeof relations_variants
  relations_media: typeof relations_media
  relations_policies: typeof relations_policies
  relations_gift_cards_rels: typeof relations_gift_cards_rels
  relations_gift_cards: typeof relations_gift_cards
  relations_pages: typeof relations_pages
  relations_payments_blocks_manual_details: typeof relations_payments_blocks_manual_details
  relations_payments_blocks_manual: typeof relations_payments_blocks_manual
  relations_payments: typeof relations_payments
  relations_locations: typeof relations_locations
  relations_shipping_blocks_custom_shipping: typeof relations_shipping_blocks_custom_shipping
  relations_shipping: typeof relations_shipping
  relations_exports_texts: typeof relations_exports_texts
  relations_exports: typeof relations_exports
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_jobs_log: typeof relations_payload_jobs_log
  relations_payload_jobs: typeof relations_payload_jobs
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
